---
name: Go
on:
  pull_request:
  push:
    branches:
      - main
      - "release-*"

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

# Minimal permissions to be inherited by any job that don't declare it's own permissions
permissions:
  contents: read

jobs:
  supportedVersions:
    name: Fetch supported Go versions
    runs-on: ubuntu-latest
    outputs:
        supported_versions: ${{ steps.matrix.outputs.supported_versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read supported_go_versions.txt
        id: matrix
        run: |
            versions=$(cat supported_go_versions.txt)
            matrix="[$(echo "$versions" | sed 's/\(.*\)/"\1"/' | paste -s -d,)]"
            echo "supported_versions=$matrix" >> $GITHUB_OUTPUT

  test:
    name: Tests
    strategy:
      matrix:
        go_version: ${{ fromJSON(needs.supportedVersions.outputs.supported_versions) }}
        os: [ubuntu-latest, macos-latest, windows-latest]  # Matrix for OS
    runs-on: ${{ matrix.os }}
    needs: supportedVersions
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ matrix.go_version }}

      - name: Cache Go modules
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: v1-go${{ matrix.go_version }}-${{ matrix.os }}

      - name: Set environment variables for platform without cgo
        run: |
          echo "Setting environment variables for ${{ matrix.os }}"
          if [[ ${{ matrix.os }} == 'macos-latest' ]]; then
            echo "GOOS=darwin" >> $GITHUB_ENV
            echo "GOARCH=amd64" >> $GITHUB_ENV
          elif [[ ${{ matrix.os }} == 'windows-latest' ]]; then
            echo "GOOS=windows" >> $GITHUB_ENV
            echo "GOARCH=amd64" >> $GITHUB_ENV
            echo "TMPDIR=C:\\Temp" >> $GITHUB_ENV
          elif [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            echo "GOOS=linux" >> $GITHUB_ENV
            echo "GOARCH=amd64" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run tests and check license
        run: make check_license test
        env:
          CI: true
          CGO_ENABLED: 1

      - name: Run style and unused
        if: ${{ matrix.go_version == '1.22' }}
        run: make style unused
